{% set data = load_setup_py_data() %}

package:
    name    : timechart
    version : {{ data.get('version') }}

source:
    path: ..

requirements:
    build:
      - python
      - setuptools
      - pydm >=1.6.0

    run:
      - six
      - python
      - pydm >=1.6.0

test:
    imports:
      - timechart

about:
  home: https://github.com/slaclab/timechart
  license: SLAC Open License
  summary: Charting Tool based on PyDM
